spring.application.name=similarproducts
server.port=${SERVER_PORT:5000}
spring.threads.virtual.enabled=true

products.api.base-url=${PRODUCTS_API_BASE_URL:http://localhost:3001}
products.api.timeout=${PRODUCTS_API_TIMEOUT:3s}
products.cache.ttl=${PRODUCTS_CACHE_TTL:5m}
